databases:
  - name: kodara-hq-db
    databaseName: kodara_hq
    user: kodara_hq_user
    plan: free

services:
  - type: web
    name: kodara-hq-web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_HOST
        fromDatabase:
          name: kodara-hq-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: kodara-hq-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: kodara-hq-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: kodara-hq-db
          property: password
      - key: POSTGRES_PORT
        fromDatabase:
          name: kodara-hq-db
          property: port
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
